print ('Please, enter your name')
Name = str(input())
print ('Please, enter your age')
Age = int(input())
print ('Please, enter your ocupations')
Job = str(input())
Lempl = [Name, Age, Job]
print (Lempl)
print("Press Enter to continue ...")
input()